Repository keonwoo98/webserv, pull requests merged in 2022-12, with the labels that each got.

#9 Message Class 생성
  .gitignore
  CMakeLists.txt
  Makefile
  app/CMakeLists.txt
  app/main.cpp
  docs/index.html
  includes/client_socket.hpp
  includes/kqueue_handler.hpp
  includes/message/body.hpp
  includes/message/header.hpp
  includes/message/http_version.hpp
  includes/message/response_message.hpp
  includes/message/status_line.hpp
  includes/request/request_header.hpp
  includes/request/request_message.hpp
  includes/server_socket.hpp
  includes/socket.hpp
  includes/status_code.hpp
  includes/webserv.hpp
  sources/CMakeLists.txt
  sources/client_socket.cpp
  sources/kqueue_handler.cpp
  sources/message/body.cpp
  sources/message/header.cpp
  sources/message/http_version.cpp
  sources/message/response_message.cpp
  sources/message/status_line.cpp
  sources/server_socket.cpp
  sources/socket.cpp
  sources/webserv.cpp
  test
  test/CMakeLists.txt
  test/header_test.cpp
  test/http_version_test.cpp
  test/main.cpp
  test/response_message_test.cpp
  test/socket_test.cpp
  test/status_line_test.cpp
Labels: 🎯 Feature

#11 DELETE 메서드 구현
  includes/delete_method.hpp
  sources/CMakeLists.txt
  sources/delete_method.cpp
  test/CMakeLists.txt
  test/delete_method_test.cpp
Labels: 🎯 Feature, ✅ Test

#20 date 기능 구현
  sources/CMakeLists.txt
  sources/date.cpp
Labels: 🎯 Feature

#24 CGI
  html/cgi-bin/gugu.php
  html/cgi-bin/hello.php
  includes/cgi_handler.hpp
  sources/CMakeLists.txt
  sources/cgi_handler.cpp
  test/get_method_test.cpp
Labels: 🎯 Feature

#34 Dkim2
  includes/request_message.hpp
  sources/request_message.cpp
  sources/request_parser.cpp
  test/sample_client.cpp
Labels: 🎯 Feature, ✅ Test

#33 Location ,Server add getter, setter
  includes/location.hpp
  includes/server.hpp
  sources/config_parser.cpp
  sources/location.cpp
  sources/server.cpp
Labels: 🎯 Feature, :recycle: refactor

#31 POST 메서드 구현
  app/CMakeLists.txt
  includes/post_method.hpp
  sources/CMakeLists.txt
  sources/post_method.cpp
  test/CMakeLists.txt
  test/post_method_test.cpp
Labels: 🎯 Feature, ✅ Test

#40 merge conflict
  .gitignore
  Makefile
  app/CMakeLists.txt
  backup/request_message copy.cpp
  backup/request_message copy.hpp
  backup/request_parser copy.cpp
  includes/client_socket.hpp
  includes/http_exception.hpp
  includes/kqueue_handler.hpp
  includes/message.hpp
  includes/request_chunked_message.hpp
  includes/request_message.hpp
  includes/request_parser.hpp
  includes/response_message.hpp
  includes/webserv.hpp
  index.html
  sources/CMakeLists.txt
  sources/client_socket.cpp
  sources/http_exception.cpp
  sources/kqueue_handler.cpp
  sources/message.cpp
  sources/request_chunked_message.cpp
  sources/request_message.cpp
  sources/request_parser.cpp
  sources/response_message.cpp
  sources/webserv.cpp
  test/request_parsing.cpp
  test/sample_client.cpp
Labels: :recycle: Refactor

#26 Config file parsing
  .gitignore
  default.conf
  example.conf
  includes/config_parser.hpp
  includes/location.hpp
  includes/server.hpp
  sources/config_parser.cpp
  sources/location.cpp
  sources/main.cpp
  sources/server.cpp
Labels: 🎯 Feature

#47 Feat/build
  Makefile
  app/CMakeLists.txt
  app/main.cpp
  backup/request_message copy.cpp
  backup/request_message copy.hpp
  backup/request_parser copy.cpp
  build/bin/webserv_test
  conf/default.conf
  conf/example.conf
  docs/cgi-bin/gugu.php
  docs/cgi-bin/hello.php
  index.html
  sources/CMakeLists.txt
  test/CMakeLists.txt
  test/header_test.cpp
  test/http_version_test.cpp
  test/request_parsing.cpp
  test/response_message_test.cpp
  test/sample_client.cpp
  test/status_line_test.cpp
Labels: :recycle: Refactor

#45 CollectEvents기능 세분화
  app/main.cpp
  conf/example.conf
  includes/config_parser.hpp
  includes/kqueue_handler.hpp
  includes/server_socket.hpp
  includes/webserv.hpp
  sources/client_socket.cpp
  sources/config_parser.cpp
  sources/kqueue_handler.cpp
  sources/server_socket.cpp
  sources/webserv.cpp
Labels: :recycle: Refactor

#44 getaddrinfo 사용해서 server socket 생성하기
  .gitignore
  default.conf
  example.conf
  includes/config_parser.hpp
  includes/location.hpp
  includes/server.hpp
  includes/server_socket.hpp
  includes/webserv.hpp
  sources/client_socket.cpp
  sources/config_parser.cpp
  sources/location.cpp
  sources/main.cpp
  sources/server.cpp
  sources/server_socket.cpp
  sources/webserv.cpp
Labels: 🎯 Feature

#51 Refactor/config
  app/main.cpp
  includes/config_parser.hpp
  includes/server.hpp
  sources/config_parser.cpp
  sources/server_socket.cpp
Labels: :recycle: Refactor

#52 feat: uri 출력 연산자 오버로딩 추가
  includes/uri.hpp
  sources/uri.cpp
Labels: 🎯 Feature

#62 디렉토리 구조 변경에 따른 Makefile 수정
  Makefile
  includes/config/config_parser.hpp
  includes/config/location.hpp
  includes/config/server.hpp
  includes/core/client_socket.hpp
  includes/core/kqueue_handler.hpp
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  includes/core/webserv.hpp
  includes/exception/http_exception.hpp
  includes/request/request_chunked_message.hpp
  includes/request/request_message.hpp
  includes/request/request_parser.hpp
  includes/request/uri.hpp
  includes/response/cgi_handler.hpp
  includes/response/delete_method.hpp
  includes/response/get_method.hpp
  includes/response/post_method.hpp
  includes/response/response_message.hpp
  includes/response/status_code.hpp
  sources/CMakeLists.txt
  sources/config/config_parser.cpp
  sources/config/location.cpp
  sources/config/server.cpp
  sources/core/client_socket.cpp
  sources/core/kqueue_handler.cpp
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
  sources/exception/http_exception.cpp
  sources/request/request_chunked_message.cpp
  sources/request/request_message.cpp
  sources/request/request_parser.cpp
  sources/request/uri.cpp
  sources/response/cgi_handler.cpp
  sources/response/date.cpp
  sources/response/delete_method.cpp
  sources/response/get_method.cpp
  sources/response/post_method.cpp
  sources/response/response_message.cpp
Labels: 📃 Document

#65 response message 리팩토링 & 기능 추가
  includes/response/date.h
  includes/response/header.h
  includes/response/http_version.h
  includes/response/response_message.hpp
  includes/response/status_code.hpp
  includes/response/status_line.h
  sources/CMakeLists.txt
  sources/response/date.cpp
  sources/response/header.cpp
  sources/response/http_version.cpp
  sources/response/response_message.cpp
  sources/response/status_line.cpp
  test/CMakeLists.txt
  test/header_test.cpp
  test/response_message_test.cpp
  test/status_line_test.cpp
Labels: 🎯 Feature

#71 Refactor/socket
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  includes/exception/core_exception.h
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
  test/CMakeLists.txt
  test/server_socket_test.cpp
Labels: :recycle: Refactor

#77 Feat/Conf
  .vscode/settings.json
  app/main.cpp
  conf/example.conf
  includes/config/config_parser.hpp
  includes/config/server_info.hpp
  includes/core/client_socket.hpp
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  sources/config/config_parser.cpp
  sources/config/server_info.cpp
  sources/core/client_socket.cpp
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
Labels: 🎯 Feature

#78 Refactor/webserv
  includes/core/client_socket.hpp
  includes/core/server_socket.hpp
  includes/core/udata.h
  includes/core/webserv.hpp
  includes/request/request_message.hpp
  includes/response/response_message.hpp
  includes/response/status_line.h
  sources/CMakeLists.txt
  sources/core/client_socket.cpp
  sources/core/udata.cpp
  sources/core/webserv.cpp
  sources/request/request_message.cpp
  sources/response/response_message.cpp
  sources/response/status_line.cpp
Labels: :recycle: Refactor

#79 refactor: use_type을 사용하도록 변경
  app/main.cpp
  includes/core/client_socket.hpp
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  includes/core/webserv.hpp
  sources/core/client_socket.cpp
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
Labels: :recycle: Refactor

#81 Test/refactor
  CMakeLists.txt
  test/delete_method_test.cpp
  test/get_method_test.cpp
  test/header_test.cpp
  test/post_method_test.cpp
  test/response_message_test.cpp
  test/server_socket_test.cpp
  test/socket_test.cpp
  test/status_line_test.cpp
Labels: ✅ Test

#83 Refactor/config
  conf/example.conf
  includes/config/location_info.hpp
  includes/config/server_info.hpp
  sources/config/config_parser.cpp
  sources/config/location_info.cpp
  sources/config/server_info.cpp
Labels: :recycle: Refactor

#118 Refact/socket
  CMakeLists.txt
  includes/core/event_executor.hpp
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  includes/core/webserv.hpp
  sources/CMakeLists.txt
  sources/core/event_executor.cpp
  sources/core/server_socket.cpp
  sources/core/webserv.cpp
  test/CMakeLists.txt
  test/header_test.cpp
  test/kqueue_handler_test.cpp
  test/response_event_test.cpp
  test/response_message_test.cpp
  test/status_line_test.cpp
Labels: :recycle: Refactor

#120 refactor: kqueue handler 사용하도록 변경
  includes/core/event_executor.hpp
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
Labels: :recycle: Refactor

#123 Feat/log
  Makefile
  app/main.cpp
  includes/core/kqueue_handler.hpp
  includes/core/logger.hpp
  includes/core/socket.hpp
  includes/core/udata.hpp
  includes/core/webserv.hpp
  includes/exception/core_exception.hpp
  includes/exception/http_exception.hpp
  includes/response/response_message.hpp
  sources/CMakeLists.txt
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/logger.cpp
  sources/core/socket.cpp
  sources/core/udata.cpp
  sources/core/webserv.cpp
  sources/exception/http_exception.cpp
  sources/request/request_message.cpp
  sources/response/response_message.cpp
Labels: 🎯 Feature

#134 feat: Response Message Add Location 기능 추가
  includes/response/response_message.hpp
  sources/response/response_message.cpp
Labels: 🎯 Feature

#139 feat: host 값을 ip 문자열로 바꿔주는 기능
  includes/core/socket.hpp
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  test/CMakeLists.txt
  test/core/socket_addr.cpp
Labels: 🎯 Feature

#140 fix: access log 버그 수정
  sources/core/event_executor.cpp
Labels: 🎯 Feature

#144 Refactor / Config
  includes/config/error_pages.hpp
  includes/config/index.hpp
  includes/config/location_info.hpp
  includes/config/server_info.hpp
  sources/config/error_pages.cpp
  sources/config/index.cpp
  sources/config/location_info.cpp
  sources/config/server_info.cpp
Labels: :recycle: Refactor

#142 Refact/server info
  includes/config/server_info.hpp
  includes/core/client_socket.hpp
  includes/core/event_executor.hpp
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  includes/request/request_parser.hpp
  sources/config/server_info.cpp
  sources/core/client_socket.cpp
  sources/core/event_executor.cpp
  sources/core/resolve_uri.cpp
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
  sources/request/request_parser.cpp
  sources/request/request_validation.cpp
Labels: :recycle: Refactor

#151 Feat/conf/server info plus
  includes/config/location_info.hpp
  includes/config/server_info.hpp
  sources/config/location_info.cpp
  sources/config/server_info.cpp
  test/config/config_utils_method_test.cpp
Labels: 🎯 Feature

#150 Feat/error page
  includes/config/error_pages.hpp
  includes/core/event_executor.hpp
  includes/response/response_message.hpp
  sources/config/error_pages.cpp
  sources/core/event_executor.cpp
  sources/response/response_message.cpp
  test/CMakeLists.txt
  test/config/config_utils_method_test.cpp
  test/docs/error/error.html
  test/response/build_response_test.cpp
  test/response/send_response_test.cpp
Labels: 🎯 Feature, ✅ Test

#152 Feat/server info return
  includes/config/config_parser.hpp
  includes/config/config_utils.hpp
  includes/config/location_info.hpp
  includes/config/server_info.hpp
  sources/config/config_parser.cpp
  sources/config/config_utils.cpp
  sources/config/error_pages.cpp
  sources/config/index.cpp
  sources/config/location_info.cpp
  sources/config/server_info.cpp
  test/config/config_utils_method_test.cpp
Labels: 🎯 Feature, :recycle: Refactor

#168 Refacotr/response
  includes/core/event_executor.hpp
  includes/response/response_message.hpp
  includes/response/status_line.hpp
  sources/core/event_executor.cpp
  sources/core/webserv.cpp
  sources/response/response_message.cpp
  sources/response/status_line.cpp
Labels: 🎯 Feature, 🐛 BugFix

#175 fix 좀비프로세스 생기는 오류 수정
  includes/core/kqueue_handler.hpp
  includes/exception/core_exception.hpp
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/webserv.cpp
  sources/response/cgi_handler.cpp
Labels: 🐛 BugFix
