Repository keonwoo98/webserv, pull requests merged in 2023-01, with the labels that each got.

#172 Feat/http
  includes/config/error_pages.hpp
  includes/const/character_color.hpp
  includes/const/character_const.hpp
  includes/const/html.hpp
  includes/core/event_executor.hpp
  includes/core/fd_handler.hpp
  sources/CMakeLists.txt
  sources/config/error_pages.cpp
  sources/core/event_executor.cpp
  sources/core/fd_handler.cpp
  sources/request/request_validation.cpp
  sources/response/delete_method.cpp
  sources/response/make_autoindex_html.cpp
  test/CMakeLists.txt
  test/http_method/delete_method_test.cpp
Labels: 🎯 Feature, :recycle: Refactor

#181 Refactor/webserv
  includes/core/event_executor.hpp
  includes/core/kqueue_handler.hpp
  includes/core/logger.hpp
  includes/core/webserv.hpp
  sources/core/client_socket.cpp
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/logger.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
  sources/exception/http_exception.cpp
Labels: 🎯 Feature, 🐛 BugFix

#192 fix: client_max_body_size 옵션 ningx와 일치하게 수정
  sources/config/location_info.cpp
  sources/config/server_info.cpp
Labels: 🐛 BugFix

#194 Refactor/webserv
  includes/const/html.hpp
  includes/core/event_executor.hpp
  includes/core/kqueue_handler.hpp
  includes/core/webserv.hpp
  includes/exception/core_exception.hpp
  includes/response/response_message.hpp
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/server_socket.cpp
  sources/core/webserv.cpp
  sources/response/cgi_handler.cpp
  sources/response/cgi_parser.cpp
  sources/response/response_message.cpp
  test.cpp
Labels: :recycle: Refactor

#193 Feat/head
  includes/const/html.hpp
  includes/core/auto_index.hpp
  includes/response/response_message.hpp
  sources/CMakeLists.txt
  sources/config/server_info.cpp
  sources/core/auto_index.cpp
  sources/core/event_executor.cpp
  sources/response/response_message.cpp
Labels: 🎯 Feature, :recycle: Refactor

#198 fix: 메모리 누수
  includes/response/cgi_handler.hpp
  sources/core/kqueue_handler.cpp
  sources/response/cgi_handler.cpp
Labels: 🐛 BugFix

#204 fix: close fd
  app/main.cpp
  sources/core/event_executor.cpp
Labels: 🐛 BugFix

#218 Fix/tester
  conf/test1.conf
  includes/core/client_socket.hpp
  includes/core/udata.hpp
  includes/core/webserv.hpp
  includes/response/header.hpp
  includes/response/response_message.hpp
  sources/core/client_socket.cpp
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/server_socket.cpp
  sources/core/webserv.cpp
  sources/request/request_message.cpp
  sources/response/cgi_handler.cpp
  sources/response/header.cpp
  sources/response/response_message.cpp
Labels: 🐛 BugFix, :recycle: Refactor

#225 Refactor/websev
  YoupiBanane/directory/youpi.bad_extension
  YoupiBanane/directory/youpi.bla
  YoupiBanane/put_test/temp
  app/main.cpp
  conf/tester.conf
  includes/core/cgi_handler.hpp
  includes/core/cgi_parser.hpp
  includes/core/event_executor.hpp
  includes/core/kqueue_handler.hpp
  includes/core/logger.hpp
  includes/core/server_socket.hpp
  includes/core/socket.hpp
  includes/core/udata.hpp
  includes/core/webserv.hpp
  includes/exception/core_exception.hpp
  includes/request/request_parser.hpp
  includes/request/uri.hpp
  includes/response/delete_method.hpp
  includes/response/get_method.hpp
  includes/response/post_method.hpp
  includes/response/response_message.hpp
  includes/util/file_util.hpp
  includes/util/kevent_util.hpp
  sources/CMakeLists.txt
  sources/core/cgi_handler.cpp
  sources/core/cgi_parser.cpp
  sources/core/event_executor.cpp
  sources/core/kqueue_handler.cpp
  sources/core/logger.cpp
  sources/core/resolve_uri.cpp
  sources/core/server_socket.cpp
  sources/core/socket.cpp
  sources/core/webserv.cpp
  sources/request/request_message.cpp
  sources/request/request_parser.cpp
  sources/request/uri.cpp
  sources/response/get_method.cpp
  sources/response/post_method.cpp
  sources/util/file_util.cpp
  sources/util/kevent_util.cpp
Labels: 🎯 Feature, :recycle: Refactor

#220 fix: cgi 예외처리
  app/main.cpp
  includes/core/event_executor.hpp
  sources/core/cgi_handler.cpp
  sources/core/event_executor.cpp
Labels: 🐛 BugFix

#228 fix: compile error
  sources/core/event_executor.cpp
  sources/core/webserv.cpp
Labels: 🐛 BugFix

#232 Fix/errorpage
  conf/tester.conf
  docs/error/4xx.html
  sources/core/cgi_handler.cpp
  sources/core/event_executor.cpp
Labels: 🐛 BugFix
